### ISSUE TITLE
Sheaf Type

### ISSUE THREAD

**Issue by BlueF16** [itc-addons/ITC_Land_Systems#11]
Whichever Sheaf Type I select it seems to always fire a parallel sheaf. 

My BTY Setup: 
Gun 1:  123456
Gun 2:  124456
Gun 3: 125456
---------------------------
Fire mission Settings:
Type: Grid
Grid: 127510
Sheaf Type: Converged
----------------------------
All guns are issued the same deflection.

Am i doing something wrong.

**Comment by toadball** [comment]
Reproduced with example given, we will examine further: At this time I don't believe this is user error.
Thanks for bringing this to our attention.

**Comment by YannikH** [comment]
Issue identified and fixed, hotfix pushed to workshop.
