### ISSUE TITLE
Conflicting addon itc_land_bcs in 'itc_land_bcs\', previous definition in 'itc_land_aps\'

### ISSUE THREAD

**Issue by ryeyan619** [itc-addons/ITC_Land_Systems#12]
my dedicated server is giving me this error on my .rpt file.

**Comment by toadball** [comment]
Yeah, it's from a WIP feature being included by accident with some very obvious mistakes in the CfgPatches by nobody in particular (Yax).
We'll have it fixed in a release this evening / tomorrow.

Keeping open until update is published on workshop.

**Comment by toadball** [comment]
Marking closed: Issue should have been resolved in one of last years updates. If it persists raise a new issue.
