### ISSUE TITLE
Spike: TV effect is applied to all weapons as long as Spike launcher is carried

### ISSUE THREAD

**Issue by VKing6** [itc-addons/ITC_Land_Systems#17]
The black and white TV effect is applied to the gunner view for any other weapon used by the player (vehicle weapons not tested) as long as the Spike launcher is carried.

**Comment by SemperShpee** [comment]
tested further. the TV effect is applied to the ADS view for every weapon after the launcher has been equipped. vehicle weapons apply as well while the launcher is equipped.
Getting into the gunner seat of a vehicle without the launcher equipped and going into ADS fixes this problem.

**Comment by toadball** [comment]
Resolved in latest build
