### ISSUE TITLE
[Request] CRAM Standalone

### ISSUE THREAD

**Issue by PaxJaromeMalues** [itc-addons/ITC_Land_Systems#19]
Hi, like in the title, would it be possible for the team to provide part of the itc-land-systems as a standalone mod?

for example as itc_cram or something along the lines?

AFAIK there is currently absolutely nothing comparable to you C-RAM functionality out there. Neither as mod nor as script.

**Comment by PaxJaromeMalues** [comment]
Is this team still active?

**Comment by toadball** [comment]
We are still working on the mod when time and motivation allows for it.
As for the request, we are not planning on doing this in the immediate future
