### ISSUE TITLE
minimum angle of fire

### ISSUE THREAD

**Issue by PaxJaromeMalues** [itc-addons/ITC_Land_Systems#7]
CWIS should have a minimum angle of fire under which it will not/or stop engaging projectiles. About 10-15° from the ground? Shells are usually shot at friendly positions so having the CWIS kill the shells is good, but only if friendlies are not killed by the CWIS after that.

**Comment by toadball** [comment]
Projectiles that are below 100m will not be targeted, we've found this typically prevents CIWS from engaging at too low an angle.
