### ISSUE TITLE
Fire Solution too high Quadrant

### ISSUE THREAD

**Issue by BadDestiny** [itc-addons/ITC_Land_Systems#8]
The refraction of the Quadrant is too high for the vehicles it gives me Solution above 1480 or higher.
The Max Quadrant for the vehicles is: 

- Zamak 1159
- Sholef 1438
- Seara MLRS 1196
- Sochor 1420

RHS Compats: 

- Akatsiya 1382
- Paladin 1430

**Comment by toadball** [comment]
BTABS have been recalculated to take this into account for Sholef and Sochor variants. Will be reviewed again later on down the line.
RHS compats will have new BTABs generated taking these limits into consideration as part of the next round of updates to them following release of ITC Land v1.2
